package net.jamesjennison.klippercompanion

/** A MyMiniFactory category (the API's `cat` filter); [children] are its direct sub-categories. */
data class MmfCategory(val id: Int, val name: String, val children: List<MmfCategory> = emptyList())

/**
 * MyMiniFactory's category tree, two levels deep, snapshotted from GET /api/v2/categories on 2026-09-24. Shipped as data because the live
 * endpoint is a 1.4 MB, 981-entry tree. Left out on purpose: the store flag (Discover's Free/Paid filter), PDF-only, adult, and seasonal one-offs.
 * An id that MyMiniFactory later retires simply returns no results.
 */
object MmfCategories {
    val tree: List<MmfCategory> = listOf(
    MmfCategory(288, "Accessibility", listOf(MmfCategory(1091, "Hope3D by Sam Suchin"), MmfCategory(110, "Oxfam"), MmfCategory(1004, "Prosthetic & Orthotic"), MmfCategory(1259, "Safety Equipment"), MmfCategory(1006, "Specialized Technical Aid"))),
    MmfCategory(913, "Architecture", listOf()),
    MmfCategory(1014, "Board Games", listOf(MmfCategory(1016, "Catan"), MmfCategory(523, "Chess Sets"))),
    MmfCategory(366, "Build a 3D Printer", listOf(MmfCategory(1271, "3DPrintMill"), MmfCategory(590, "Anet"), MmfCategory(949, "Anycubic"), MmfCategory(599, "Atom"), MmfCategory(960, "Calibration parts - test print"), MmfCategory(595, "CraftBot"), MmfCategory(605, "Da Vinci"), MmfCategory(597, "Dagoma"), MmfCategory(600, "Eustathios"), MmfCategory(1000, "Filament guide"), MmfCategory(588, "FlashForge"), MmfCategory(592, "Geeetech"), MmfCategory(596, "Kossel"), MmfCategory(604, "M3D"), MmfCategory(594, "Makerbot"), MmfCategory(593, "Printrbot"), MmfCategory(493, "Prusa"), MmfCategory(606, "QIDI"), MmfCategory(495, "Rapide Lite"), MmfCategory(494, "Rigidbot"), MmfCategory(608, "Robox"), MmfCategory(1001, "Spool holder"), MmfCategory(672, "STARTT"), MmfCategory(602, "TEVO"), MmfCategory(598, "Tronxy"), MmfCategory(591, "Ultimaker"), MmfCategory(601, "Up!"), MmfCategory(607, "Velleman"), MmfCategory(603, "Wanhao"))),
    MmfCategory(86, "Education", listOf(MmfCategory(166, "Art"), MmfCategory(154, "Biology"), MmfCategory(162, "Chemistry"), MmfCategory(953, "Design & Technology"), MmfCategory(109, "Education Architecture"), MmfCategory(970, "Elementary Schools"), MmfCategory(164, "Geography"), MmfCategory(972, "High Schools"), MmfCategory(344, "History"), MmfCategory(969, "Kindergartens"), MmfCategory(163, "Mathematics"), MmfCategory(971, "Middle Schools"), MmfCategory(68, "Music & Instruments"), MmfCategory(165, "Physics"), MmfCategory(973, "University"))),
    MmfCategory(104, "Fan Art", listOf(MmfCategory(67, "Action Figures"), MmfCategory(957, "Adventure Time"), MmfCategory(927, "Angry Birds"), MmfCategory(1159, "Apex Legends"), MmfCategory(533, "Bethesda"), MmfCategory(355, "Celebrities"), MmfCategory(541, "Destiny"), MmfCategory(435, "Doom"), MmfCategory(532, "Fallout"), MmfCategory(733, "Game Of Thrones"), MmfCategory(442, "Hearthpwn Contest"), MmfCategory(537, "Hearthstone"), MmfCategory(105, "Logos"), MmfCategory(538, "Minecraft"), MmfCategory(539, "Monster Hunter"), MmfCategory(544, "Other fan art"), MmfCategory(536, "Overwatch"), MmfCategory(496, "Pokemon"), MmfCategory(543, "Valiant"), MmfCategory(540, "Vikings"))),
    MmfCategory(58, "Fashion & Accessories", listOf(MmfCategory(143, "Bags & Cases"), MmfCategory(169, "Clothes"), MmfCategory(140, "Footwear"), MmfCategory(147, "Glasses"), MmfCategory(357, "Keyrings"))),
    MmfCategory(59, "Gadgets & Electronics", listOf(MmfCategory(943, "Arduino, Raspberry & DIY"), MmfCategory(328, "Audio"), MmfCategory(113, "Cameras & Photography"), MmfCategory(329, "Computer"), MmfCategory(360, "Drones, Helicopters & Planes"), MmfCategory(363, "eCigarettes"), MmfCategory(94, "Phones & Tablets"), MmfCategory(393, "Robotics"), MmfCategory(941, "Smart Home"), MmfCategory(507, "Video Games & VR Accessories"), MmfCategory(275, "Wearable Tech"))),
    MmfCategory(57, "Home & Decor", listOf(MmfCategory(150, "Garden & Outdoors"), MmfCategory(335, "Home Decor"), MmfCategory(149, "Organizer & Storage"), MmfCategory(252, "Workshop & Tools"))),
    MmfCategory(291, "Jewellery", listOf(MmfCategory(148, "Bracelets"), MmfCategory(405, "Earrings"), MmfCategory(426, "Fan art jewellery"), MmfCategory(359, "Fine jewellery"), MmfCategory(430, "MMF Jewellery Shop"), MmfCategory(145, "Pendants"), MmfCategory(406, "Rings"), MmfCategory(439, "Élodie Ortisset - Jewellery Design"))),
    MmfCategory(119, "Props & Cosplay", listOf(MmfCategory(340, "Cosplay Accessories"), MmfCategory(542, "Light Swords"), MmfCategory(155, "Masks and Helmets"), MmfCategory(156, "Replica Guns"), MmfCategory(304, "Replica Swords & Knives"))),
    MmfCategory(120, "RC Cars", listOf(MmfCategory(1282, "Accessories Exterior"), MmfCategory(1283, "Accessories Interior"), MmfCategory(1291, "Accessories Spare Parts"), MmfCategory(1274, "Buggy"), MmfCategory(1273, "Crawler"), MmfCategory(1292, "Drag Racing"), MmfCategory(1275, "Drifting"), MmfCategory(1276, "Monster Truck"), MmfCategory(1278, "Scale 1:10"), MmfCategory(1279, "Scale 1:14"), MmfCategory(1280, "Scale 1:16"), MmfCategory(1281, "Scale 1:24"), MmfCategory(1299, "Scale 1:6"), MmfCategory(1277, "Scale 1:8"))),
    MmfCategory(112, "Scan the World", listOf(MmfCategory(176, "Africa"), MmfCategory(137, "All"), MmfCategory(228, "Asia"), MmfCategory(553, "Australia"), MmfCategory(772, "Brain Catalogue"), MmfCategory(1012, "Embodi3D"), MmfCategory(177, "Europe"), MmfCategory(178, "North America"), MmfCategory(1129, "Oceania"), MmfCategory(731, "Private Collection"), MmfCategory(131, "South America"))),
    MmfCategory(88, "Spare Parts", listOf(MmfCategory(831, "Battery Covers"), MmfCategory(452, "Bearings"), MmfCategory(902, "Cars & Other Vehicles"), MmfCategory(502, "Computers & Electronics"), MmfCategory(830, "DIY / Gardening Tools"), MmfCategory(445, "Ikea"), MmfCategory(823, "Kitchen Appliances"), MmfCategory(832, "Photography"), MmfCategory(829, "Vacuum Cleaners / Floor care"), MmfCategory(828, "Washing Machines / Dryers"))),
    MmfCategory(56, "Sports & Outdoor", listOf(MmfCategory(71, "Airsoft"), MmfCategory(550, "Climbing"), MmfCategory(114, "Cycling"), MmfCategory(962, "Fishing"), MmfCategory(342, "Outdoor"), MmfCategory(551, "Snowboards, Skateboards & Skate"), MmfCategory(69, "Sport"))),
    MmfCategory(1015, "Tabletop", listOf(MmfCategory(617, "Accessories"), MmfCategory(1304, "Anime & Manga"), MmfCategory(1145, "Busts"), MmfCategory(785, "Characters & Creatures"), MmfCategory(1319, "Full Color"), MmfCategory(1325, "Game Bundles"), MmfCategory(1324, "Storage"), MmfCategory(787, "Terrain"), MmfCategory(1313, "Trench Crusade"), MmfCategory(786, "Vehicles & Machines"), MmfCategory(1306, "Wargaming"))),
    MmfCategory(60, "Toys", listOf(MmfCategory(462, "Articulated"), MmfCategory(1309, "Cuties"), MmfCategory(1308, "Marbles"), MmfCategory(1307, "Mechanical Marvels"), MmfCategory(100, "Puzzles & Games"), MmfCategory(529, "Scaled Models"))),
    )
    fun find(id: Int?): MmfCategory? = id?.let { wanted -> tree.firstNotNullOfOrNull { t -> if (t.id == wanted) t else t.children.firstOrNull { it.id == wanted } } }
}
