package net.jamesjennison.klippercompanion

// GENERATED by scripts/bundle_vendor_profiles.py - do not edit by hand; rerun the script.
// One entry per bundled OrcaSlicer profile pack (app/src/main/assets/slicer_profiles/<assetDir>). The enum is persisted by
// name(), so existing names are never renamed or removed; new models are only ever appended.
enum class SlicingPrinterModel { SNAPMAKER_U1, ELEGOO_CENTAURI_CARBON, BAMBU_GENERIC, PRUSA_GENERIC, GENERIC_KLIPPER, PRUSA_XL_5T, BAMBU_A1_MINI, BAMBU_A2L, BAMBU_H2C, BAMBU_H2D, BAMBU_H2D_PRO, BAMBU_H2S, BAMBU_P1P, BAMBU_P1S, BAMBU_P2S, BAMBU_X1, BAMBU_X1_CARBON, BAMBU_X1E, BAMBU_X2D, PRUSA_MK4S, PRUSA_MK3_5, PRUSA_MK3S, PRUSA_MINI, PRUSA_MINI_IS, PRUSA_CORE_ONE, PRUSA_CORE_ONE_L, PRUSA_XL }

enum class SlicingVendor(val label: String) { SNAPMAKER("Snapmaker"), ELEGOO("Elegoo"), BAMBU("Bambu Lab"), PRUSA("Prusa"), GENERIC("Generic") }

/** verifiedOnHardware: this pack has produced a real print on a real printer of this model; everything else is profile-only. */
data class SlicingModelInfo(val model: SlicingPrinterModel, val label: String, val vendor: SlicingVendor, val assetDir: String, val verifiedOnHardware: Boolean)

object SlicingModelCatalog {
    val all: List<SlicingModelInfo> = listOf(
        SlicingModelInfo(SlicingPrinterModel.SNAPMAKER_U1, "Snapmaker U1", SlicingVendor.SNAPMAKER, "snapmaker_u1", true),
        SlicingModelInfo(SlicingPrinterModel.ELEGOO_CENTAURI_CARBON, "Elegoo Centauri Carbon (OpenCentauri COSMOS)", SlicingVendor.ELEGOO, "elegoo_centauri_carbon_cosmos", true),
        SlicingModelInfo(SlicingPrinterModel.BAMBU_GENERIC, "Bambu Lab A1", SlicingVendor.BAMBU, "bambu_generic", false),
        SlicingModelInfo(SlicingPrinterModel.BAMBU_A1_MINI, "Bambu Lab A1 mini", SlicingVendor.BAMBU, "bambu_a1_mini", false),
        SlicingModelInfo(SlicingPrinterModel.BAMBU_A2L, "Bambu Lab A2L", SlicingVendor.BAMBU, "bambu_a2l", false),
        SlicingModelInfo(SlicingPrinterModel.BAMBU_H2C, "Bambu Lab H2C", SlicingVendor.BAMBU, "bambu_h2c", false),
        SlicingModelInfo(SlicingPrinterModel.BAMBU_H2D, "Bambu Lab H2D", SlicingVendor.BAMBU, "bambu_h2d", false),
        SlicingModelInfo(SlicingPrinterModel.BAMBU_H2D_PRO, "Bambu Lab H2D Pro", SlicingVendor.BAMBU, "bambu_h2d_pro", false),
        SlicingModelInfo(SlicingPrinterModel.BAMBU_H2S, "Bambu Lab H2S", SlicingVendor.BAMBU, "bambu_h2s", false),
        SlicingModelInfo(SlicingPrinterModel.BAMBU_P1P, "Bambu Lab P1P", SlicingVendor.BAMBU, "bambu_p1p", false),
        SlicingModelInfo(SlicingPrinterModel.BAMBU_P1S, "Bambu Lab P1S", SlicingVendor.BAMBU, "bambu_p1s", false),
        SlicingModelInfo(SlicingPrinterModel.BAMBU_P2S, "Bambu Lab P2S", SlicingVendor.BAMBU, "bambu_p2s", false),
        SlicingModelInfo(SlicingPrinterModel.BAMBU_X1, "Bambu Lab X1", SlicingVendor.BAMBU, "bambu_x1", false),
        SlicingModelInfo(SlicingPrinterModel.BAMBU_X1_CARBON, "Bambu Lab X1 Carbon", SlicingVendor.BAMBU, "bambu_x1_carbon", false),
        SlicingModelInfo(SlicingPrinterModel.BAMBU_X1E, "Bambu Lab X1E", SlicingVendor.BAMBU, "bambu_x1e", false),
        SlicingModelInfo(SlicingPrinterModel.BAMBU_X2D, "Bambu Lab X2D", SlicingVendor.BAMBU, "bambu_x2d", false),
        SlicingModelInfo(SlicingPrinterModel.PRUSA_CORE_ONE, "Prusa CORE One", SlicingVendor.PRUSA, "prusa_core_one", false),
        SlicingModelInfo(SlicingPrinterModel.PRUSA_CORE_ONE_L, "Prusa CORE One L", SlicingVendor.PRUSA, "prusa_core_one_l", false),
        SlicingModelInfo(SlicingPrinterModel.PRUSA_MINI, "Prusa MINI / MINI+", SlicingVendor.PRUSA, "prusa_mini", false),
        SlicingModelInfo(SlicingPrinterModel.PRUSA_MINI_IS, "Prusa MINI IS", SlicingVendor.PRUSA, "prusa_mini_is", false),
        SlicingModelInfo(SlicingPrinterModel.PRUSA_MK3_5, "Prusa MK3.5", SlicingVendor.PRUSA, "prusa_mk3_5", false),
        SlicingModelInfo(SlicingPrinterModel.PRUSA_MK3S, "Prusa MK3S / MK3S+", SlicingVendor.PRUSA, "prusa_mk3s", false),
        SlicingModelInfo(SlicingPrinterModel.PRUSA_GENERIC, "Prusa MK4", SlicingVendor.PRUSA, "prusa_generic", false),
        SlicingModelInfo(SlicingPrinterModel.PRUSA_MK4S, "Prusa MK4S", SlicingVendor.PRUSA, "prusa_mk4s", false),
        SlicingModelInfo(SlicingPrinterModel.PRUSA_XL, "Prusa XL (single tool)", SlicingVendor.PRUSA, "prusa_xl", false),
        SlicingModelInfo(SlicingPrinterModel.PRUSA_XL_5T, "Prusa XL 5T (five tools)", SlicingVendor.PRUSA, "prusa_xl_5t", false),
        SlicingModelInfo(SlicingPrinterModel.GENERIC_KLIPPER, "Generic Klipper", SlicingVendor.GENERIC, "generic_klipper", true),
    )
    private val byModel = all.associateBy { it.model }
    fun info(model: SlicingPrinterModel): SlicingModelInfo = byModel.getValue(model)
}
