package net.jamesjennison.klippercompanion

import org.json.JSONArray
import org.junit.Assert.*
import org.junit.Test
import java.io.StringWriter

// CONSTRUCTED fixtures, not captures. Pairing replies follow what upstream OrcaSlicer 5298e49d src/slic3r/Utils/UltiMaker.cpp
// compares against (`"Ultimaker S5"`, `{"id","key"}`, `{"message": "unknown"|"authorized"|"unauthorized"}`, `"ok"`). The
// cluster-API lists carry only the fields Cura 72521b7 plugins/UM3NetworkPrinting reads (ClusterPrinterStatus.py,
// ClusterPrintJobStatus.py): uuid, status, enabled; name, status, printer_uuid / assigned_to, time_total, time_elapsed.
class UltiMakerApiTest {
    @Test fun sendingIsGatedOffAndSendsNothing() {
        assertFalse(UltiMakerApi.START_VERIFIED)
        assertFalse(startVerifiedFor(PrinterKind.ULTIMAKER))
        val refusal = assertThrows(ApiFailure::class.java) { UltiMakerApi.requireStartVerified("cube.gcode") }
        assertTrue(refusal.message!!.startsWith("Nothing was sent"))
        assertTrue(refusal.message!!.contains("isn't verified on real hardware"))
    }

    @Test fun variantRule() {
        assertTrue(UltiMakerApi.isUpstreamVariant("\"Ultimaker S5\""))
        assertTrue(UltiMakerApi.isUpstreamVariant("\"Ultimaker 3 Extended\""))
        assertFalse("upstream accepts the S5 exactly", UltiMakerApi.isUpstreamVariant("\"Ultimaker S7\""))
        assertEquals("Ultimaker S7", UltiMakerApi.variantName("\"Ultimaker S7\""))
        assertNull(UltiMakerApi.variantName("<html>"))
    }

    @Test fun pairingReplies() {
        assertEquals(UltiMakerApi.Credentials("abc123", "k3y"), UltiMakerApi.parseCredentials("""{"id": "abc123", "key": "k3y"}"""))
        assertNull(UltiMakerApi.parseCredentials("""{"id": "abc123", "key": ""}"""))
        assertNull(UltiMakerApi.parseCredentials("nope"))
        assertEquals(UltiMakerApi.AuthStatus.WAITING, UltiMakerApi.authStatus("""{"message": "unknown"}"""))
        assertEquals(UltiMakerApi.AuthStatus.AUTHORIZED, UltiMakerApi.authStatus("""{"message": "authorized"}"""))
        assertEquals(UltiMakerApi.AuthStatus.UNAUTHORIZED, UltiMakerApi.authStatus("""{"message": "unauthorized"}"""))
        assertEquals(UltiMakerApi.AuthStatus.UNKNOWN, UltiMakerApi.authStatus("{}"))
        assertTrue(UltiMakerApi.isVerified("\"ok\""))
        assertTrue(UltiMakerApi.isVerified("""{"message": "ok"}"""))
        assertFalse(UltiMakerApi.isVerified("""{"message": "Authorization required."}"""))
        assertNull(UltiMakerApi.authProblem(UltiMakerApi.AuthStatus.AUTHORIZED, true))
        assertNotNull(UltiMakerApi.authProblem(UltiMakerApi.AuthStatus.AUTHORIZED, false))
        assertTrue(UltiMakerApi.authProblem(UltiMakerApi.AuthStatus.WAITING, false)!!.contains("Waiting"))
        assertEquals(listOf("application", "user"), UltiMakerApi.authRequestFields().keys.toList())
    }

    @Test fun printTimeFollowsUpstreamsPatterns() {
        assertEquals(3723L, UltiMakerApi.printTimeSeconds(sequenceOf("G1", "; estimated printing time (normal mode) = 1h 2m 3s")))
        assertEquals(125L, UltiMakerApi.printTimeSeconds(sequenceOf("; estimated printing time (normal mode) = 2m 5s")))
        assertEquals("seconds alone and days aren't read upstream", 0L, UltiMakerApi.printTimeSeconds(sequenceOf("; estimated printing time (normal mode) = 45s", "; estimated printing time (normal mode) = 1d 2h 3m 4s")))
    }

    @Test fun griffinHeaderCleanUp() {
        val file = listOf("; leading comment", ";START_OF_HEADER", ";PRINT.TIME:0", "; generated by OrcaSlicer 2.3.0 on 2026-09-29 at 10:11:12", ";END_OF_HEADER", "G28")
        val out = StringWriter()
        assertTrue(UltiMakerApi.writeGriffinCompatible(file.joinToString("\n").reader().buffered(), out, 3723))
        assertEquals(";START_OF_HEADER\n;PRINT.TIME:3723\n; generated by OrcaSlicer 2.3.0 on 2026-09-29 at 10-11-12\n;END_OF_HEADER\nG28\n", out.toString())
        assertFalse("no header: refused, not uploaded empty", UltiMakerApi.writeGriffinCompatible("G28\nG1 X1".reader().buffered(), StringWriter(), 0))
    }

    private val printers = JSONArray("""[{"uuid":"p-1","friendly_name":"S5","machine_variant":"Ultimaker S5","status":"printing","enabled":true}]""")

    @Test fun statusFromTheClusterApi() {
        val jobs = JSONArray("""[
            {"uuid":"j-0","name":"queued.gcode","status":"queued","time_total":100,"time_elapsed":0,"assigned_to":"p-1"},
            {"uuid":"j-1","name":"cube.gcode","status":"printing","time_total":1000,"time_elapsed":250,"printer_uuid":"p-1"}]""")
        val s = UltiMakerApi.snapshot(printers, jobs)
        assertEquals("printing", s.state); assertTrue(s.ready)
        assertEquals("cube.gcode", s.filename); assertEquals(0.25f, s.progress, 0.0001f); assertEquals(250.0, s.printDuration!!, 0.0)
        assertNull("no temperatures over the LAN", s.nozzle)
    }

    @Test fun statesAsCuraNamesThem() {
        assertEquals("standby", UltiMakerApi.snapshot(JSONArray("""[{"uuid":"p","status":"idle"}]"""), JSONArray()).state)
        assertEquals("unknown", UltiMakerApi.snapshot(JSONArray("""[{"uuid":"p","status":"idle","enabled":false}]"""), JSONArray()).state)
        assertEquals("unknown", UltiMakerApi.snapshot(JSONArray(), JSONArray()).state)
        assertEquals("paused", UltiMakerApi.stateName("printing", "paused"))
        assertEquals("complete", UltiMakerApi.stateName("printing", "wait_cleanup"))
        assertEquals("cancelled", UltiMakerApi.stateName("printing", "wait_cleanup", cleanupAfterAbort = true))
        assertEquals("cancelled", UltiMakerApi.stateName("printing", "aborted_wait_cleanup"))
        assertEquals("error", UltiMakerApi.stateName("printing", "failed_post_print"))
        assertEquals("printing", UltiMakerApi.stateName("pre_print", null))
        assertEquals("busy", UltiMakerApi.stateName("maintenance", null))
        assertEquals("unknown", UltiMakerApi.stateName("unreachable", null))
    }
}
