package net.jamesjennison.klippercompanion

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.compose.LocalLifecycleOwner
import kotlinx.coroutines.*

@Composable fun ConfigFilePanel(address: String, connected: Boolean, close: () -> Unit, factory: (String) -> ConfigFileReader = { Moonraker(it) }) {
    var content by remember(address) { mutableStateOf<ConfigFileContent?>(null) }
    var note by remember(address) { mutableStateOf("Loading configuration…") }
    var epoch by remember(address) { mutableIntStateOf(0) }
    val scope = rememberCoroutineScope()
    val lifecycle = LocalLifecycleOwner.current.lifecycle
    fun load() {
        if (!connected) { content = null; note = "Disconnected. Connect to read the configuration."; return }
        val ticket = ++epoch
        note = "Loading configuration…"
        scope.launch {
            val reader = try { factory(address) } catch (_: Exception) { if (ticket == epoch) note = "Configuration unavailable."; return@launch }
            try {
                val result = withContext(Dispatchers.IO) { reader.configFile() }
                if (ticket != epoch) return@launch
                content = result
                note = "Loaded ${result.filename}."
            } catch (e: CancellationException) { throw e }
            catch (e: Exception) { if (ticket == epoch) { content = null; note = e.message ?: "Configuration unavailable." } }
            finally { reader.close() }
        }
    }
    LaunchedEffect(address, connected, lifecycle) {
        if (lifecycle.currentState.isAtLeast(Lifecycle.State.RESUMED)) load()
    }
    Dialog(onDismissRequest = close, properties = DialogProperties(usePlatformDefaultWidth = false)) {
        Surface(Modifier.fillMaxWidth().fillMaxHeight(0.9f).padding(12.dp), shape = MaterialTheme.shapes.large) {
            Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                Text("Configuration", style = MaterialTheme.typography.titleLarge)
                Text("Printer: $address")
                Text("Read-only view. Editing, saving and restart are not available yet.", style = MaterialTheme.typography.bodySmall)
                Text(note, modifier = Modifier.testTag("config-status"), style = MaterialTheme.typography.bodySmall)
                content?.let { file ->
                    Column(Modifier.weight(1f).verticalScroll(rememberScrollState()), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                        Text("Your configuration", style = MaterialTheme.typography.titleMedium)
                        Text(file.userSection, fontFamily = FontFamily.Monospace, style = MaterialTheme.typography.bodySmall, modifier = Modifier.testTag("config-user-section"))
                        if (file.hasAutoSection) {
                            Text("Auto-generated by SAVE_CONFIG", style = MaterialTheme.typography.titleMedium)
                            Text(file.autoSection, fontFamily = FontFamily.Monospace, style = MaterialTheme.typography.bodySmall, modifier = Modifier.testTag("config-auto-section"))
                        }
                    }
                } ?: Spacer(Modifier.weight(1f))
                Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                    TextButton({ load() }, enabled = connected, modifier = Modifier.testTag("refresh-config")) { Text("Refresh") }
                    TextButton(close) { Text("Close") }
                }
            }
        }
    }
}
