// Generated by scripts/generate_design_tokens.py from design/tokens/nozzle.tokens.json and design/terminology/glossary.json. Do not edit.
package com.nozzleitall.design

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.text.font.FontWeight

/** One palette per appearance. Roles, not raw colours: screens ask for `text`, never a hex value. */
data class NozzlePalette(
    val background: Color,
    val surface: Color,
    val surfaceRaised: Color,
    val surfaceSunken: Color,
    val line: Color,
    val lineStrong: Color,
    val text: Color,
    val textMuted: Color,
    val accent: Color,
    val onAccent: Color,
    val heat: Color,
    val focus: Color,
    val danger: Color,
    val onDanger: Color,
)

/** Colour for each shared printer state (PrinterState.glossaryId without the 'state.' prefix). */
data class NozzleStatusColors(
    val offline: Color,
    val connecting: Color,
    val starting: Color,
    val ready: Color,
    val printing: Color,
    val paused: Color,
    val finished: Color,
    val cancelled: Color,
    val error: Color,
    val unknown: Color,
) {
    fun forState(id: String): Color = when (id.removePrefix("state.")) {
        "offline" -> offline
        "connecting" -> connecting
        "starting" -> starting
        "ready" -> ready
        "printing" -> printing
        "paused" -> paused
        "finished" -> finished
        "cancelled" -> cancelled
        "error" -> error
        "unknown" -> unknown
        else -> unknown
    }
}

object NozzleTokens {
    const val VERSION = "1.0.0"
    val darkPalette = NozzlePalette(
        background = Color(0xFF0D1114),
        surface = Color(0xFF14191D),
        surfaceRaised = Color(0xFF1E2429),
        surfaceSunken = Color(0xFF0A0D0F),
        line = Color(0xFF2A3138),
        lineStrong = Color(0xFF4A545B),
        text = Color(0xFFEEF2F4),
        textMuted = Color(0xFF9AA5AA),
        accent = Color(0xFFA78BFA),
        onAccent = Color(0xFF0D1114),
        heat = Color(0xFFF2754E),
        focus = Color(0xFFC4B5FD),
        danger = Color(0xFFFB7185),
        onDanger = Color(0xFF0D1114),
    )
    val darkStatus = NozzleStatusColors(
        offline = Color(0xFF9AA5AA),
        connecting = Color(0xFF93C5FD),
        starting = Color(0xFF93C5FD),
        ready = Color(0xFF5EEAD4),
        printing = Color(0xFFA78BFA),
        paused = Color(0xFFFBBF24),
        finished = Color(0xFF86EFAC),
        cancelled = Color(0xFF9AA5AA),
        error = Color(0xFFFB7185),
        unknown = Color(0xFFFCD34D),
    )
    val lightPalette = NozzlePalette(
        background = Color(0xFFF6F7F9),
        surface = Color(0xFFFFFFFF),
        surfaceRaised = Color(0xFFEEF1F3),
        surfaceSunken = Color(0xFFE6EAED),
        line = Color(0xFFD5DBDE),
        lineStrong = Color(0xFF9AA5AA),
        text = Color(0xFF0D1114),
        textMuted = Color(0xFF4F5A61),
        accent = Color(0xFF6D28D9),
        onAccent = Color(0xFFFFFFFF),
        heat = Color(0xFFC2410C),
        focus = Color(0xFF6D28D9),
        danger = Color(0xFFBE123C),
        onDanger = Color(0xFFFFFFFF),
    )
    val lightStatus = NozzleStatusColors(
        offline = Color(0xFF4F5A61),
        connecting = Color(0xFF1D4ED8),
        starting = Color(0xFF1D4ED8),
        ready = Color(0xFF0F766E),
        printing = Color(0xFF6D28D9),
        paused = Color(0xFF92400E),
        finished = Color(0xFF166534),
        cancelled = Color(0xFF4F5A61),
        error = Color(0xFFBE123C),
        unknown = Color(0xFF854D0E),
    )
    val brandViolet = Color(0xFF8B5CF6)
    val printOrange = Color(0xFFF2754E)

    /** Spacing on a 4 dp grid. */
    object Space {
        val s0 = 0.dp
        val s1 = 4.dp
        val s2 = 8.dp
        val s3 = 12.dp
        val s4 = 16.dp
        val s5 = 20.dp
        val s6 = 24.dp
        val s8 = 32.dp
        val s10 = 40.dp
        val s12 = 48.dp
        val s16 = 64.dp
    }
    object Radius {
        val chip = 999.dp
        val small = 8.dp
        val control = 12.dp
        val card = 16.dp
        val panel = 20.dp
    }
    object Size {
        val touchTarget = 48.dp
        val desktopTarget = 32.dp
        val icon = 20.dp
        val iconLarge = 28.dp
        val railWidth = 88.dp
        val contentMax = 1280.dp
    }
    object Border {
        val hairline = 1.dp
        val focus = 3.dp
        val selected = 2.dp
    }
    object Motion {
        const val quickMillis = 120
        const val standardMillis = 200
        const val emphasisMillis = 320
    }
    /** Type scale: family key (display/body/mono), size, line height, weight, letter spacing in em. */
    data class TypeStyle(val family: String, val size: androidx.compose.ui.unit.TextUnit, val lineHeight: androidx.compose.ui.unit.TextUnit, val weight: FontWeight, val trackingEm: Float)
    object Type {
        val display = TypeStyle("display", 32.sp, 40.sp, FontWeight(700), -0.01f)
        val headline = TypeStyle("display", 24.sp, 32.sp, FontWeight(700), -0.01f)
        val title = TypeStyle("display", 18.sp, 26.sp, FontWeight(600), 0f)
        val body = TypeStyle("body", 15.sp, 22.sp, FontWeight(400), 0f)
        val bodySmall = TypeStyle("body", 13.sp, 18.sp, FontWeight(400), 0f)
        val label = TypeStyle("body", 13.sp, 16.sp, FontWeight(600), 0.02f)
        val metric = TypeStyle("mono", 22.sp, 28.sp, FontWeight(500), 0f)
        val metricSmall = TypeStyle("mono", 14.sp, 18.sp, FontWeight(500), 0f)
    }
}
