package net.jamesjennison.klippercompanion

import androidx.compose.ui.test.*
import androidx.compose.ui.test.junit4.createComposeRule
import org.junit.Assert.*
import org.junit.Rule
import org.junit.Test

class ConfigFilePanelDeviceTest {
    @get:Rule val compose = createComposeRule()
    @Test fun loadsAndDisplaysBothSections() {
        val reader = object : ConfigFileReader {
            override fun configFile() = ConfigFileContent("printer.cfg", "[printer]\nkinematics: corexy", "#*# <-- SAVE_CONFIG -->\n#*# [bed_mesh default]")
            override fun close() {}
        }
        compose.setContent { CompanionTheme { ConfigFilePanel("http://fixture.local/", true, {}, { reader }) } }
        compose.waitUntil(5000) { compose.onAllNodesWithTag("config-user-section").fetchSemanticsNodes().isNotEmpty() }
        compose.onNodeWithTag("config-auto-section").assertExists()
        compose.onNodeWithText("Auto-generated by SAVE_CONFIG").assertExists()
    }
    @Test fun noAutoSectionIsNotShown() {
        val reader = object : ConfigFileReader {
            override fun configFile() = ConfigFileContent("printer.cfg", "[printer]\nkinematics: corexy", "")
            override fun close() {}
        }
        compose.setContent { CompanionTheme { ConfigFilePanel("http://fixture.local/", true, {}, { reader }) } }
        compose.waitUntil(5000) { compose.onAllNodesWithTag("config-user-section").fetchSemanticsNodes().isNotEmpty() }
        compose.onNodeWithTag("config-auto-section").assertDoesNotExist()
    }
    @Test fun disconnectedShowsExplicitMessageWithoutQuerying() {
        var queried = false
        val reader = object : ConfigFileReader {
            override fun configFile(): ConfigFileContent { queried = true; throw ApiFailure("Should not be called") }
            override fun close() {}
        }
        compose.setContent { CompanionTheme { ConfigFilePanel("http://fixture.local/", false, {}, { reader }) } }
        compose.onNodeWithText("Disconnected. Connect to read the configuration.").assertExists()
        assertFalse(queried)
    }
}
