#!/usr/bin/env python3
"""Generates every platform's design tokens and terminology from the family's single sources of truth:

  design/tokens/nozzle.tokens.json      colours, status colours, type, spacing, radius, motion
  design/terminology/glossary.json      product names, state/route/action labels, explanations, internal words

Outputs (never edit by hand):
  desktop + app NozzleTokens.kt   -> Compose Desktop and Android (identical Compose code)
  printer-api/.../Glossary.kt     -> shared Kotlin terminology (Desktop, Android, Stock helper)
  web/src/design/tokens.css, tokens.ts, glossary.ts  -> the Web App
  site-src/assets/tokens.css      -> the public website

Also enforces WCAG 2.2 contrast for every colour that declares a "contrast" target.

  python3 scripts/generate_design_tokens.py          write outputs
  python3 scripts/generate_design_tokens.py --check  exit 1 if anything is stale or a contrast target fails
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOKENS = json.loads((ROOT / "design/tokens/nozzle.tokens.json").read_text())
GLOSSARY = json.loads((ROOT / "design/terminology/glossary.json").read_text())
HEADER = "Generated by scripts/generate_design_tokens.py from design/tokens/nozzle.tokens.json and design/terminology/glossary.json. Do not edit."


def luminance(hex_colour: str) -> float:
    h = hex_colour.lstrip("#")
    channels = [int(h[i:i + 2], 16) / 255 for i in (0, 2, 4)]
    lin = [c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4 for c in channels]
    return 0.2126 * lin[0] + 0.7152 * lin[1] + 0.0722 * lin[2]


def contrast(a: str, b: str) -> float:
    la, lb = sorted((luminance(a), luminance(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


def check_contrast() -> list:
    failures = []
    for mode in ("dark", "light"):
        palette = TOKENS["color"][mode]
        for name, tok in palette.items():
            rule = tok.get("contrast")
            if not rule:
                continue
            for bg in rule["on"]:
                ratio = contrast(tok["$value"], palette[bg]["$value"])
                if ratio < rule["min"]:
                    failures.append(f"{mode} {name} on {bg}: {ratio:.2f} < {rule['min']}")
        rule = TOKENS["status"]["contrast"]
        for name, tok in TOKENS["status"][mode].items():
            for bg in rule["on"]:
                ratio = contrast(tok["$value"], palette[bg]["$value"])
                if ratio < rule["min"]:
                    failures.append(f"{mode} status {name} on {bg}: {ratio:.2f} < {rule['min']}")
    return failures


def camel(name: str) -> str:
    parts = name.replace("_", "-").split("-")
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])


def pascal(name: str) -> str:
    c = camel(name)
    return c[:1].upper() + c[1:]


def argb(hex_colour: str) -> str:
    return "0xFF" + hex_colour.lstrip("#").upper()


def kotlin_tokens() -> str:
    lines = [f"// {HEADER}", "package com.nozzleitall.design", "", "import androidx.compose.ui.graphics.Color",
             "import androidx.compose.ui.unit.dp", "import androidx.compose.ui.unit.sp", "import androidx.compose.ui.text.font.FontWeight", "",
             "/** One palette per appearance. Roles, not raw colours: screens ask for `text`, never a hex value. */",
             "data class NozzlePalette("]
    roles = list(TOKENS["color"]["dark"].keys())
    for r in roles:
        lines.append(f"    val {camel(r)}: Color,")
    lines.append(")")
    lines.append("")
    lines.append("/** Colour for each shared printer state (PrinterState.glossaryId without the 'state.' prefix). */")
    lines.append("data class NozzleStatusColors(")
    for s in TOKENS["status"]["dark"].keys():
        lines.append(f"    val {camel(s)}: Color,")
    lines.append(") {")
    lines.append("    fun forState(id: String): Color = when (id.removePrefix(\"state.\")) {")
    for s in TOKENS["status"]["dark"].keys():
        lines.append(f"        \"{s}\" -> {camel(s)}")
    lines.append("        else -> unknown")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("object NozzleTokens {")
    lines.append(f"    const val VERSION = \"{TOKENS['meta']['version']}\"")
    for mode in ("dark", "light"):
        lines.append(f"    val {mode}Palette = NozzlePalette(")
        for r in roles:
            lines.append(f"        {camel(r)} = Color({argb(TOKENS['color'][mode][r]['$value'])}),")
        lines.append("    )")
        lines.append(f"    val {mode}Status = NozzleStatusColors(")
        for s, tok in TOKENS["status"][mode].items():
            lines.append(f"        {camel(s)} = Color({argb(tok['$value'])}),")
        lines.append("    )")
    lines.append(f"    val brandViolet = Color({argb(TOKENS['brand']['violet']['$value'])})")
    lines.append(f"    val printOrange = Color({argb(TOKENS['brand']['print-orange']['$value'])})")
    lines.append("")
    lines.append("    /** Spacing on a 4 dp grid. */")
    lines.append("    object Space {")
    for k, v in TOKENS["space"].items():
        if k.startswith("$"):
            continue
        lines.append(f"        val s{k} = {v}.dp")
    lines.append("    }")
    lines.append("    object Radius {")
    for k, v in TOKENS["radius"].items():
        lines.append(f"        val {camel(k)} = {v}.dp")
    lines.append("    }")
    lines.append("    object Size {")
    for k, v in TOKENS["size"].items():
        lines.append(f"        val {camel(k)} = {v}.dp")
    lines.append("    }")
    lines.append("    object Border {")
    for k, v in TOKENS["border"].items():
        lines.append(f"        val {camel(k)} = {v}.dp")
    lines.append("    }")
    lines.append("    object Motion {")
    for k, v in TOKENS["motion"].items():
        if k.startswith("$"):
            continue
        lines.append(f"        const val {camel(k)}Millis = {v['duration']}")
    lines.append("    }")
    lines.append("    /** Type scale: family key (display/body/mono), size, line height, weight, letter spacing in em. */")
    lines.append("    data class TypeStyle(val family: String, val size: androidx.compose.ui.unit.TextUnit, val lineHeight: androidx.compose.ui.unit.TextUnit, val weight: FontWeight, val trackingEm: Float)")
    lines.append("    object Type {")
    for k, v in TOKENS["type"].items():
        if k.startswith("$"):
            continue
        lines.append(f"        val {camel(k)} = TypeStyle(\"{v['family']}\", {v['size']}.sp, {v['line']}.sp, FontWeight({v['weight']}), {v['tracking']}f)")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def kotlin_glossary() -> str:
    def esc(s: str) -> str:
        return s.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$")
    lines = [f"// {HEADER}", "package com.nozzleitall.printer", "",
             "/** A user-facing term shared by every Nozzle It All platform. */",
             "data class Term(val id: String, val label: String, val description: String = \"\", val confirm: String = \"\", val plural: String = \"\", val destructive: Boolean = false)",
             "", "object Glossary {", f"    const val VERSION = \"{GLOSSARY['version']}\""]
    for k, v in GLOSSARY["product"].items():
        lines.append(f"    const val PRODUCT_{camel(k).upper()} = \"{esc(v)}\"")
    lines.append("    val terms: Map<String, Term> = listOf(")
    for tid, t in GLOSSARY["terms"].items():
        lines.append(f"        Term(\"{tid}\", \"{esc(t['label'])}\", \"{esc(t.get('description', ''))}\", \"{esc(t.get('confirm', ''))}\", \"{esc(t.get('plural', ''))}\", {str(t.get('destructive', False)).lower()}),")
    lines.append("    ).associateBy { it.id }")
    lines.append("    val explanations: Map<String, String> = mapOf(")
    for k, v in GLOSSARY["explanations"].items():
        lines.append(f"        \"{k}\" to \"{esc(v)}\",")
    lines.append("    )")
    lines.append("    /** Implementation words that must not appear in everyday UI copy. */")
    lines.append("    val internalWords: List<String> = listOf(" + ", ".join(f"\"{esc(w)}\"" for w in GLOSSARY["internal-words"]["words"]) + ")")
    lines.append("    fun label(id: String): String = terms[id]?.label ?: error(\"Missing glossary term: $id\")")
    lines.append("    fun term(id: String): Term = terms[id] ?: error(\"Missing glossary term: $id\")")
    lines.append("}")
    lines.append("")
    lines.append("val PrinterState.label: String get() = Glossary.label(glossaryId)")
    lines.append("val PrinterState.description: String get() = Glossary.term(glossaryId).description")
    lines.append("val ConnectionRoute.label: String get() = Glossary.label(glossaryId)")
    lines.append("val FirmwareFamily.label: String get() = Glossary.label(glossaryId)")
    lines.append("val PrinterAction.label: String get() = Glossary.label(glossaryId)")
    return "\n".join(lines) + "\n"


def css_tokens(scope_comment: str) -> str:
    out = [f"/* {HEADER} {scope_comment} */", ":root{color-scheme:dark;"]

    def block(mode: str) -> str:
        parts = [f"--{r}:{t['$value']};" for r, t in TOKENS["color"][mode].items()]
        parts += [f"--status-{s}:{t['$value']};" for s, t in TOKENS["status"][mode].items()]
        return "".join(parts)
    fam = {k: ",".join(f'"{f}"' if " " in f else f for f in v["$value"]) for k, v in TOKENS["font"].items()}
    out.append(block("dark"))
    out.append(f"--brand-violet:{TOKENS['brand']['violet']['$value']};--print-orange:{TOKENS['brand']['print-orange']['$value']};")
    out.append("".join(f"--font-{k}:{v};" for k, v in fam.items()))
    out.append("".join(f"--space-{k}:{v}px;" for k, v in TOKENS["space"].items() if not k.startswith("$")))
    out.append("".join(f"--radius-{k}:{v}px;" for k, v in TOKENS["radius"].items()))
    out.append("".join(f"--size-{k}:{v}px;" for k, v in TOKENS["size"].items()))
    for k, v in TOKENS["type"].items():
        if k.startswith("$"):
            continue
        out.append(f"--type-{k}:{v['weight']} {v['size'] / 16:.4g}rem/{v['line'] / v['size']:.3g} var(--font-{v['family']});")
    for k, v in TOKENS["motion"].items():
        if k.startswith("$"):
            continue
        out.append(f"--motion-{k}:{v['duration']}ms {v['easing']};")
    out.append(f"--shadow-floating:{TOKENS['elevation']['floating']['shadow']};")
    out.append("}")
    light = block("light")
    out.append(f"@media (prefers-color-scheme:light){{:root:not([data-theme=dark]){{color-scheme:light;{light}}}}}")
    out.append(f":root[data-theme=light]{{color-scheme:light;{light}}}")
    out.append(f":root[data-theme=dark]{{color-scheme:dark;{block('dark')}}}")
    out.append("@media (prefers-reduced-motion:reduce){:root{--motion-quick:0ms linear;--motion-standard:0ms linear;--motion-emphasis:0ms linear}}")
    return "\n".join(out) + "\n"


def ts_tokens() -> str:
    data = {"version": TOKENS["meta"]["version"], "status": {m: {k: v["$value"] for k, v in TOKENS["status"][m].items()} for m in ("dark", "light")},
            "statusIcon": {k: v["icon"] for k, v in TOKENS["status"]["dark"].items()}, "space": {k: v for k, v in TOKENS["space"].items() if not k.startswith("$")},
            "radius": TOKENS["radius"], "size": TOKENS["size"]}
    return f"// {HEADER}\nexport const tokens = {json.dumps(data, indent=2)} as const;\n"


def ts_glossary() -> str:
    data = {"version": GLOSSARY["version"], "product": GLOSSARY["product"], "terms": GLOSSARY["terms"], "explanations": GLOSSARY["explanations"],
            "internalWords": GLOSSARY["internal-words"]["words"]}
    body = json.dumps(data, indent=2, ensure_ascii=False)
    return (f"// {HEADER}\nexport const glossary = {body} as const;\n"
            "export type TermId = keyof typeof glossary.terms;\n"
            "export const label = (id: TermId): string => glossary.terms[id].label;\n"
            "export const describe = (id: TermId): string => (glossary.terms[id] as { description?: string }).description ?? '';\n")


OUTPUTS = {
    "desktop/src/main/kotlin/com/nozzleitall/design/NozzleTokens.kt": kotlin_tokens,
    "app/src/main/java/com/nozzleitall/design/NozzleTokens.kt": kotlin_tokens,
    "printer-api/src/main/kotlin/com/nozzleitall/printer/Glossary.kt": kotlin_glossary,
    "web/src/design/tokens.css": lambda: css_tokens("Web App."),
    "web/src/design/tokens.ts": ts_tokens,
    "web/src/design/glossary.ts": ts_glossary,
    "site-src/assets/tokens.css": lambda: css_tokens("Public website."),
}


def main() -> int:
    check = "--check" in sys.argv
    failures = check_contrast()
    for f in failures:
        print("contrast:", f, file=sys.stderr)
    stale = []
    for rel, fn in OUTPUTS.items():
        path = ROOT / rel
        content = fn()
        if check:
            if not path.exists() or path.read_text() != content:
                stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    for s in stale:
        print("stale:", s, "(run python3 scripts/generate_design_tokens.py)", file=sys.stderr)
    if failures or stale:
        return 1
    print(f"design tokens {TOKENS['meta']['version']} / glossary {GLOSSARY['version']}: {'up to date' if check else 'generated'}; contrast targets met")
    return 0


if __name__ == "__main__":
    sys.exit(main())
