package com.nozzleitall.desktop.prepare

import org.json.JSONObject
import java.io.File

/** One bundled printer profile: what slicing needs, independent of any printer connection or credentials. */
data class PrinterProfileInfo(val id: String, val vendor: String, val model: String, val name: String, val bedW: Float, val bedD: Float,
                              val height: Float, val tools: Int, val outputs: List<String>, val familyHint: String)

/**
 * The printer profiles bundled with Nozzle It All (app/src/main/assets/slicer_profiles/index.json, generated by
 * scripts/build_profile_index.py; source and licence in its "source" block and PROVENANCE.md). Every profile can be
 * sliced and exported with no printer connected.
 */
object ProfileCatalog {
    const val DEFAULT_ID = "snapmaker_u1"

    val all: List<PrinterProfileInfo> by lazy {
        val text = ProfileCatalog::class.java.getResourceAsStream("/profiles/index.json")?.readBytes()?.decodeToString() ?: return@lazy emptyList()
        val a = JSONObject(text).getJSONArray("profiles")
        (0 until a.length()).map { a.getJSONObject(it) }.filter { it.getString("id") !in unsupported }.map { p ->
            val bed = p.getJSONArray("bed")
            PrinterProfileInfo(p.getString("id"), p.optString("vendor"), p.optString("model"), p.optString("name"), bed.getDouble(0).toFloat(), bed.getDouble(1).toFloat(),
                p.optDouble("height", 250.0).toFloat(), p.optInt("tools", 1), p.optJSONArray("outputs")?.let { o -> (0 until o.length()).map { o.getString(it) } } ?: listOf("gcode"),
                p.optString("family", "export-only"))
        }
    }

    /**
     * Profiles this app's engine can't slice yet (engine/profiles/unsupported-profiles.json), with the reason. They are
     * left out of [all], so they can't be picked; a project saved with one falls back to the default profile.
     */
    val unsupported: Map<String, String> by lazy {
        val text = ProfileCatalog::class.java.getResourceAsStream("/profiles/unsupported-profiles.json")?.readBytes()?.decodeToString() ?: return@lazy emptyMap()
        JSONObject(text).optJSONObject("profiles")?.let { o -> o.keySet().associateWith { o.getString(it) } } ?: emptyMap()
    }

    fun byId(id: String?): PrinterProfileInfo? = all.firstOrNull { it.id == id }

    /** Search by vendor or model, with the flagship U1 first. */
    fun search(query: String): List<PrinterProfileInfo> {
        val q = query.trim().lowercase()
        return all.filter { q.isEmpty() || it.vendor.lowercase().contains(q) || it.model.lowercase().contains(q) || it.name.lowercase().contains(q) }
            .sortedWith(compareBy({ it.id != DEFAULT_ID }, { it.vendor.lowercase() }, { it.model.lowercase() }))
    }

    /** Copies one profile's files out of the app's resources so the engine can read them as files. */
    fun materialize(cache: File, id: String): File {
        val dir = File(cache, "profiles/$id").apply { mkdirs() }
        listOf("machine.json", "process.json", "filament.json").forEach { name ->
            val target = File(dir, name)
            val res = ProfileCatalog::class.java.getResourceAsStream("/profiles/$id/$name") ?: throw IllegalStateException("The $id printer profile is incomplete.")
            res.use { input -> val bytes = input.readBytes(); if (!target.exists() || !target.readBytes().contentEquals(bytes)) target.writeBytes(bytes) }
        }
        return dir
    }
}
