// Generated by scripts/generate_design_tokens.py from design/tokens/nozzle.tokens.json and design/terminology/glossary.json. Do not edit.
export const tokens = {
  "version": "1.0.0",
  "status": {
    "dark": {
      "offline": "#9AA5AA",
      "connecting": "#93C5FD",
      "starting": "#93C5FD",
      "ready": "#5EEAD4",
      "printing": "#A78BFA",
      "paused": "#FBBF24",
      "finished": "#86EFAC",
      "cancelled": "#9AA5AA",
      "error": "#FB7185",
      "unknown": "#FCD34D"
    },
    "light": {
      "offline": "#4F5A61",
      "connecting": "#1D4ED8",
      "starting": "#1D4ED8",
      "ready": "#0F766E",
      "printing": "#6D28D9",
      "paused": "#92400E",
      "finished": "#166534",
      "cancelled": "#4F5A61",
      "error": "#BE123C",
      "unknown": "#854D0E"
    }
  },
  "statusIcon": {
    "offline": "ring-dashed",
    "connecting": "ring-spin",
    "starting": "ring-spin",
    "ready": "dot",
    "printing": "nozzle",
    "paused": "pause",
    "finished": "check",
    "cancelled": "stop",
    "error": "alert",
    "unknown": "question"
  },
  "space": {
    "0": 0,
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 20,
    "6": 24,
    "8": 32,
    "10": 40,
    "12": 48,
    "16": 64
  },
  "radius": {
    "chip": 999,
    "small": 8,
    "control": 12,
    "card": 16,
    "panel": 20
  },
  "size": {
    "touch-target": 48,
    "desktop-target": 32,
    "icon": 20,
    "icon-large": 28,
    "rail-width": 88,
    "content-max": 1280
  }
} as const;
